vaultServerAddress: http://a7e6e01d778c744b791150980a1b1ae3-639239178.us-west-2.elb.amazonaws.com:8200
onboardingRoleID: 1d027adc-c19c-53ef-f89e-6e727242c494
onboardingSecretID: a171db04-ad8c-7c67-bdcf-d9abf14fb205
readOnlyRoleID: a153ee13-c560-b78a-28c3-ab500e85a0bc
readOnlySecretID: 0e757e14-a2f5-eef2-57e6-f77090141f6b
offboardingSvcRoleId: 512dd9cf-e6b2-1686-ab66-02b24f62f1bc
offboardingSvcSecretId: 2cdf55dd-1bde-7bbd-b5a3-b2ba7d0ceedf
topmostParentNamespace: Tenant1
secretEngineType: kv
secretKey: password
secretValue: demo1234
keyValueSecretEngineMountPath: sys/mounts/user-secrets
kvSecretEnginePathForAWSCreds: user-secrets/data/aws
kvSecretEnginePathForGithubToken: user-secrets/data/github
sysNamespaceMountPath: sys/namespaces
internalNamespacePath: sys/namespaces/internal
externalNamespacePath: sys/namespaces/external
tenantBeingOnboarded: rakuten
githubPersonalAccessToken: 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
